### ISSUE TITLE
Project isn't twitter

### ISSUE THREAD

**Issue by tinsandsolution** [Anbui0115/Etsy-group-project#1]
why

**Comment by Sparky338** [comment]
Because voting?

**Comment by tinsandsolution** [comment]
> Closed

I am being silenced

**Comment by Sparky338** [comment]
I believe "issues" are supposed to be related to the project. We do need to remember that this will be visible to any prospective employers in the future. I imagine you were joking, but that might not come across to others that see this who weren't in our opening meeting.
